# Extraction rule templates for common use cases
# These are built-in and available in the Rule Sets page

TEMPLATES = {
    "ecommerce_product": {
        "name": "E-commerce Product",
        "description": "Extract product details from e-commerce pages",
        "rules": [
            {"name": "product_title", "selector": "h1.product-title, h1.product-name, [data-testid='product-title']", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "price", "selector": ".price, .product-price, [data-price], .amount", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "original_price", "selector": ".was-price, .original-price, .list-price", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "currency", "selector": "[itemprop='priceCurrency'], .currency", "type": "attribute", "attribute": "content", "regex": "", "multiple": False},
            {"name": "availability", "selector": "[itemprop='availability'], .stock-status, .availability", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "sku", "selector": "[itemprop='sku'], .sku, .product-code", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "description", "selector": ".product-description, .description, [itemprop='description']", "type": "html", "attribute": "", "regex": "", "multiple": False},
            {"name": "images", "selector": ".product-image img, .gallery img, [itemprop='image']", "type": "attribute", "attribute": "src", "regex": "", "multiple": True},
            {"name": "rating", "selector": "[itemprop='ratingValue'], .rating-score, .stars", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "review_count", "selector": "[itemprop='reviewCount'], .review-count", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "brand", "selector": "[itemprop='brand'], .brand, .manufacturer", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "category", "selector": ".breadcrumb, .product-category, [itemprop='category']", "type": "text", "attribute": "", "regex": "", "multiple": False},
        ],
    },
    "article_blog": {
        "name": "Article / Blog Post",
        "description": "Extract article metadata and content",
        "rules": [
            {"name": "article_title", "selector": "h1.entry-title, h1.post-title, article h1, [itemprop='headline']", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "author", "selector": ".author, .by-author, [itemprop='author'], [rel='author']", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "publish_date", "selector": "time.published, .post-date, [itemprop='datePublished']", "type": "attribute", "attribute": "datetime", "regex": "", "multiple": False},
            {"name": "modified_date", "selector": "time.updated, [itemprop='dateModified']", "type": "attribute", "attribute": "datetime", "regex": "", "multiple": False},
            {"name": "category", "selector": ".post-category, .entry-category, [itemprop='articleSection']", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "tags", "selector": ".tags a, .post-tags a, .entry-tags a", "type": "text", "attribute": "", "regex": "", "multiple": True},
            {"name": "featured_image", "selector": ".featured-image img, .post-thumbnail img, [itemprop='image']", "type": "attribute", "attribute": "src", "regex": "", "multiple": False},
            {"name": "content", "selector": ".entry-content, .post-content, article .content, [itemprop='articleBody']", "type": "html", "attribute": "", "regex": "", "multiple": False},
            {"name": "excerpt", "selector": ".excerpt, .entry-summary, [itemprop='description']", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "reading_time", "selector": ".reading-time, .read-time", "type": "text", "attribute": "", "regex": "", "multiple": False},
        ],
    },
    "local_business": {
        "name": "Local Business",
        "description": "Extract business contact info and details",
        "rules": [
            {"name": "business_name", "selector": "h1.business-name, [itemprop='name'], .company-name", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "street_address", "selector": "[itemprop='streetAddress'], .street-address", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "city", "selector": "[itemprop='addressLocality'], .locality", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "state", "selector": "[itemprop='addressRegion'], .region", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "postal_code", "selector": "[itemprop='postalCode'], .postal-code", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "country", "selector": "[itemprop='addressCountry'], .country-name", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "phone", "selector": "[itemprop='telephone'], .phone, a[href^='tel:']", "type": "attribute", "attribute": "href", "regex": "", "multiple": False},
            {"name": "email", "selector": "[itemprop='email'], .email, a[href^='mailto:']", "type": "attribute", "attribute": "href", "regex": "", "multiple": False},
            {"name": "website", "selector": "[itemprop='url'], .website a, a[href^='http']", "type": "attribute", "attribute": "href", "regex": "", "multiple": False},
            {"name": "opening_hours", "selector": "[itemprop='openingHours'], .hours, .schedule", "type": "text", "attribute": "", "regex": "", "multiple": True},
            {"name": "price_range", "selector": "[itemprop='priceRange'], .price-range", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "rating", "selector": "[itemprop='ratingValue'], .rating", "type": "text", "attribute": "", "regex": "", "multiple": False},
        ],
    },
    "job_listing": {
        "name": "Job Listing",
        "description": "Extract job posting details",
        "rules": [
            {"name": "job_title", "selector": "h1.job-title, [itemprop='title'], .position-title", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "company", "selector": "[itemprop='hiringOrganization'], .company-name, .employer", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "location", "selector": "[itemprop='jobLocation'], .job-location, .location", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "salary", "selector": "[itemprop='baseSalary'], .salary, .compensation", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "job_type", "selector": "[itemprop='employmentType'], .job-type, .employment-type", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "description", "selector": "[itemprop='description'], .job-description, .description", "type": "html", "attribute": "", "regex": "", "multiple": False},
            {"name": "requirements", "selector": ".requirements, .qualifications, [itemprop='qualifications']", "type": "html", "attribute": "", "regex": "", "multiple": False},
            {"name": "benefits", "selector": ".benefits, .perks, [itemprop='benefits']", "type": "html", "attribute": "", "regex": "", "multiple": False},
            {"name": "posted_date", "selector": "[itemprop='datePosted'], .posted-date", "type": "attribute", "attribute": "datetime", "regex": "", "multiple": False},
            {"name": "application_url", "selector": "[itemprop='applyUrl'], .apply-button a, a[href*='apply']", "type": "attribute", "attribute": "href", "regex": "", "multiple": False},
        ],
    },
    "real_estate": {
        "name": "Real Estate Listing",
        "description": "Extract property details from real estate sites",
        "rules": [
            {"name": "property_title", "selector": "h1.listing-title, [itemprop='name'], .property-title", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "price", "selector": ".price, .listing-price, [itemprop='price']", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "address", "selector": "[itemprop='address'], .address, .property-address", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "bedrooms", "selector": "[itemprop='numberOfBedrooms'], .bedrooms, .beds", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "bathrooms", "selector": "[itemprop='numberOfBathrooms'], .bathrooms, .baths", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "sqft", "selector": "[itemprop='floorSize'], .sqft, .square-feet", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "property_type", "selector": "[itemprop='propertyType'], .property-type", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "description", "selector": "[itemprop='description'], .description, .listing-description", "type": "html", "attribute": "", "regex": "", "multiple": False},
            {"name": "images", "selector": ".gallery img, .photos img, [itemprop='image']", "type": "attribute", "attribute": "src", "regex": "", "multiple": True},
            {"name": "agent_name", "selector": "[itemprop='agent'], .agent-name, .realtor", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "agent_phone", "selector": "[itemprop='telephone'], .agent-phone", "type": "attribute", "attribute": "href", "regex": "", "multiple": False},
        ],
    },
    "event_listing": {
        "name": "Event Listing",
        "description": "Extract event details",
        "rules": [
            {"name": "event_name", "selector": "h1.event-title, [itemprop='name'], .event-name", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "start_date", "selector": "[itemprop='startDate'], .event-date, .start-date", "type": "attribute", "attribute": "datetime", "regex": "", "multiple": False},
            {"name": "end_date", "selector": "[itemprop='endDate'], .end-date", "type": "attribute", "attribute": "datetime", "regex": "", "multiple": False},
            {"name": "venue", "selector": "[itemprop='location'], .venue, .location", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "address", "selector": "[itemprop='address'], .venue-address", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "description", "selector": "[itemprop='description'], .event-description", "type": "html", "attribute": "", "regex": "", "multiple": False},
            {"name": "ticket_url", "selector": "[itemprop='url'], .ticket-link a, .buy-tickets a", "type": "attribute", "attribute": "href", "regex": "", "multiple": False},
            {"name": "price", "selector": "[itemprop='price'], .ticket-price, .price", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "organizer", "selector": "[itemprop='organizer'], .organizer", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "category", "selector": "[itemprop='eventType'], .event-category", "type": "text", "attribute": "", "regex": "", "multiple": False},
        ],
    },
    "recipe": {
        "name": "Recipe",
        "description": "Extract recipe details",
        "rules": [
            {"name": "recipe_name", "selector": "h1.recipe-title, [itemprop='name'], .recipe-name", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "description", "selector": "[itemprop='description'], .recipe-description", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "prep_time", "selector": "[itemprop='prepTime'], .prep-time", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "cook_time", "selector": "[itemprop='cookTime'], .cook-time", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "total_time", "selector": "[itemprop='totalTime'], .total-time", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "servings", "selector": "[itemprop='recipeYield'], .servings, .yield", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "ingredients", "selector": "[itemprop='recipeIngredient'], .ingredients li, .ingredient", "type": "text", "attribute": "", "regex": "", "multiple": True},
            {"name": "instructions", "selector": "[itemprop='recipeInstructions'], .instructions, .directions", "type": "html", "attribute": "", "regex": "", "multiple": False},
            {"name": "nutrition", "selector": "[itemprop='nutrition'], .nutrition-info", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "image", "selector": "[itemprop='image'], .recipe-image img", "type": "attribute", "attribute": "src", "regex": "", "multiple": False},
            {"name": "author", "selector": "[itemprop='author'], .recipe-author", "type": "text", "attribute": "", "regex": "", "multiple": False},
            {"name": "rating", "selector": "[itemprop='ratingValue'], .rating", "type": "text", "attribute": "", "regex": "", "multiple": False},
        ],
    },
}
